version: "3"
services:
  kafka:
    image: antlypls/kafka:0.10.0.1
    environment:
      - KAFKA=localhost:9092
      - ZOOKEEPER=localhost:2181
    expose:
      - "2181"
      - "9092"

  spark:
    image: ricardogaspar2/spark-streaming-kafka
    volumes:
      - "~:/root/host_shared_dir" # for windows
      # - "~:/root/_host_shared_dir" # for unix
    links:
    - kafka